### ISSUE TITLE
Crash on Client Startup

### ISSUE THREAD

**Issue by Darkfiend009** [xstarlotte/sweetnotsavourymod#15]
I was firing up the new version to take a look at the changes and encountered a crash. Looks to be caused by Honey Drink:

Crash Report: https://pastebin.com/1gFiawvj
Forge: 40.0.44
SnS: 2.95

**Comment by xstarlotte** [comment]
Heya, this was a build issue, the 3.0 one has been tested outside the development environment and has 0 issues on load up or anything else I can currently see! Should get approved soon and available for download :)
