### ISSUE TITLE
Server Freezes While Launching

### ISSUE THREAD

**Issue by Darkfiend009** [xstarlotte/sweetnotsavourymod#16]
I was setting up a server for the modpack project i will be using to help test. When placing the modpack on the server, the server freezes while trying to initially launch.

I checked the latest.log and debug.log and found an error that is possibly causing the issue. 

Log: https://pastebin.com/ccrPN321

**Comment by Darkfiend009** [comment]
Update: 

I was able to get it to crash instead of freeze! Maybe this report can help further.

Crash Report: https://pastebin.com/2XfHzv7k

**Comment by xstarlotte** [comment]
Hey so, this is pretty challenging for me. I assume it will take me a long time to figure this out. I apologise but I think it will have to be removed from your modpack if it isn't working. I will update you as soon as I manage to get it working and I test it on a multiplayer server myself - it's just very very weird as to why this is happening as it is working fine when not on multiplayer :(

**Comment by Darkfiend009** [comment]
No worries. I will still help test and look at things via single player too as you update and release things :)

**Comment by xstarlotte** [comment]
Heya, so with the help of someone, the issue has been fixed and the mod should now be server compatible. ^-^ (Version 3.1)
